.gitignore
.php_cs
LICENSE
README.md
composer.json
phpunit.xml
src/bundle/DependencyInjection/EzPlatformRichTextFieldTypeExtension.php
src/bundle/EzPlatformRichTextFieldTypeBundle.php
src/bundle/Resources/config/services.yml

This PR introduces basic skeleton for RichText FieldType Bundle.
This is only the first step towards [EZP-28009](https://jira.ez.no/browse/EZP-28009), it allows adding the Bundle to `AppKernel` (with DI config placeholder).
The directory structure is as follows:
```
.
+-- src
|   +-- bundle
|   +-- lib # not available yet, future PR will introduce it
+-- tests # also not available yet
|   +-- lib
|   +-- bundle
```
**Introduced:**
Please note that links included in README will not work yet as adding all Resources from `ezpublish-kernel` RichText FieldType would clutter this PR diff.

EZP-28009: Created RichText FieldType Bundle

---

src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/018-htmlTable.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/018-htmlTable.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/018-htmlTable.xml

| **JIRA issue**     | [EZP-28967](https://jira.ez.no/browse/EZP-28967)
Description from JIRA:
>In RichText Editor, you can create line breaks (inside a paragraph) by pressing Shift + Enter. 
If you create a table using the rich text field type and type some text in a table cell then add a line break and then add some more text after saving the line break is removed.
If you add a new paragraph in the table cell by pressing Enter then delete the second line with Backspace and then you do the text + line break + text as I've written in the previous line the …

Fix EZP-28967: RichText FieldType removes line breaks inside table cells

---

src/bundle/DependencyInjection/Compiler/KernelRichTextPass.php
src/bundle/EzPlatformRichTextBundle.php

By deleting kernel services before their tags are processed, we don't need to remove them from the services they're added to as parameters.
| **JIRA issue**     | None
Increases the priority of the kernel pass. Ensures that services we remove haven't been processed for tags, and haven't been injected into other services as arguments.
Fixes the problems reported by QA on ezsystems/ezpublish-kernel#2302.

EZP-28009: Changed priority of kernel pass to avoid dealing with tags

---

tests/integration/eZ/SPI/RichTextFieldTypeIntegrationTest.php

| **JIRA issue**     | -
**TODO**:

SPI\RichTextFieldTypeIntegrationTest should be run against field type definition from ezplatform-richtext

---

src/bundle/DependencyInjection/Configuration/Parser/FieldType/RichText.php
src/bundle/DependencyInjection/EzPlatformRichTextExtension.php

| **JIRA issue**     | Related to [EZP-28009](https://jira.ez.no/browse/EZP-28009)
| **Target version** | `1.0 (master)`
| **Doc needed**     | ezsystems/developer-documentation#452
Global configuration for Custom Templates (Tags, Styles) registered directly under `ezrichtext` node (for RichText Extension) doesn't work.
Reason: When prepending SA-aware config from external bundle, the processing of
config parser occurs before bundle configuration is loaded,
so we cannot validate it at that point.
Changed also RichText SA-aware Config Parser to merge configured Custom Templates
from all relevant scopes (default, …

EZP-28009: Moved Custom Templates config validation to the Extension

---

.travis.yml
bin/.travis/prepare_ezplatform.sh
composer.json

| **JIRA issue**     | Related to [EZP-28009](https://jira.ez.no/browse/EZP-28009)
| **Target version** | `1.0`
| **Tests pass**     | no
There are no dedicated RichText behat profiles/suites
so for now enabling entire AdminUI suite.
**TODO**:

[Travis] Enabled AdminUI Behat tests

---

src/bundle/DependencyInjection/EzPlatformRichTextExtension.php
src/bundle/EzPlatformRichTextBundle.php
tests/bundle/DependencyInjection/Configuration/Parser/FieldType/RichTextTest.php
tests/integration/eZ/API/SetupFactory/LegacySetupFactory.php

| **JIRA issue**     | Related to [EZP-28009](https://jira.ez.no/browse/EZP-28009)
| **Target version** | `1.0 (master)`
This PR fixes loading of default (core) settings related to RichText package.
Loading should be done by API provided via CoreExtension (`ezpublish`) instead of RichTextExtension (`ezrichtext`).
**TODO**:

EZP-28009: Fixed loading default RichText core settings

---

composer.json

| **JIRA issue**     | Follow-up to [EZP-28009](https://jira.ez.no/browse/EZP-28009) and #11 
| **Target version** | `1.0 (master)`
Since ezsystems/ezplatform#337 has been merged a while ago, `_ezplatform_branch_for_behat_tests` can be safely changed back to `master`.
**TODO**:

EZP-28009: Changed eZ Platform branch for Behat tests to master

---

src/bundle/DependencyInjection/EzPlatformRichTextExtension.php
src/bundle/Resources/config/prepend/ezpublish.yml
src/bundle/Resources/views/themes/standard/content_view/embed_inline.html.twig
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
tests/bundle/DependencyInjection/EzPlatformRichTextExtensionTest.php

| **JIRA issue**     | [EZP-29812](https://jira.ez.no/browse/EZP-29812)
| **Required by** | ezsystems/ezplatform-admin-ui#736
| **Target version** | `1.0 (master) for eZ Platform 2.4`
This PR adds support for `embed-inline` View Type.
**TODO**:

EZP-29812: As an editor I want to embed a content item within a block element

---

src/bundle/Resources/config/prepend/ezpublish.yml
src/bundle/Resources/views/themes/standard/content_view/embed_inline.html.twig

| **JIRA issue**     | [EZP-29887](https://jira.ez.no/browse/EZP-29887)
| **Requires** | ezsystems/ezpublish-kernel#2503
| **Target version** | `1.0 for eZ Platform 2.4`
| **Tests pass**     | no, not related failure
Default view templates should be provided by ezpublish-kernel (see ezsystems/ezpublish-kernel#2503).
Defining it here makes it impossible to override by a project, due to order of merging of arrays with SA-aware config.
**TODO**:

EZP-29887: Dropped defining default embed-inline View type

---

src/bundle/Resources/config/bc/aliases.yml

| **JIRA issue**     | [EZP-30012](https://jira.ez.no/browse/EZP-30012)
| **Target version** | 1.0
`ezpublish.fieldType.ezrichtext.externalStorage` service is missing a BC layer, which is used in https://github.com/netgen/NetgenRichTextDataTypeBundle .
**TODO**:

Add missing BC alias for external storage

---

src/lib/Form/Mapper/RichTextFormMapper.php

| **JIRA issue**     | [EZP-29927](https://jira.ez.no/browse/EZP-29927)
| **Target version** | `1.0 (for eZ Platform 2.4)`
This PR fixes `RichTextFormMapper`, so translated Content Type label is visible in Create and Edit modes for RichText fields.
The fix is almost exactly the same as [the one done for repository-forms](https://github.com/ezsystems/repository-forms/pull/267/files#diff-ce34bcdffd1e219bcdb9a9cc9034d6bf). It didn't work because we've overridden the `RichTextFormMapper` in this package.
**TODO**:

EZP-29927: Content Type translation not used on RichText fields

---

src/bundle/Resources/views/RichText/embed/content.html.twig
src/bundle/Resources/views/RichText/embed/location.html.twig
src/lib/eZ/RichText/Converter/Render/Embed.php
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
tests/lib/eZ/RichText/Converter/Render/EmbedTest.php
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/002-para.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/008-orderedList.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/009-itemizedList.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/010-htmlInformaltable.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/011-htmlTable.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/033-programlisting.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/002-para.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/008-orderedList.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/009-itemizedList.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/010-htmlInformaltable.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/011-htmlTable.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/033-programlisting.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/002-para.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/008-orderedList.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/009-itemizedList.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/010-htmlInformaltable.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/011-htmlTable.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/033-programlisting.xml

| **JIRA issue**     | [EZP-29280](https://jira.ez.no/browse/EZP-29280)
| **Required by** | ezsystems/ezplatform-admin-ui#831
| **New feature**    | yes 
| **Tests pass**     |  yes
**TODO**:

EZP-29280: As an editor, I want to add anchors to RichText content

---

src/bundle/Resources/config/fieldtype_services.yml

| **JIRA issue**     | [EZP-30319](https://jira.ez.no/browse/EZP-30319)
| **Target version** | `1.0 for eZ Platform 2.4.x`
We were trying to implement default templates for `block`/`inline` custom styles. Found them here, and debugged why they were not working properly.
**TODO**:

EZP-30319: Fixed ezrichtext.style.namespace parameter usage

---

src/lib/eZ/RichText/Converter/Link.php
src/lib/eZ/RichText/Converter/Render/Template.php
tests/lib/eZ/RichText/Converter/AggregateTest.php
tests/lib/eZ/RichText/Converter/Render/TemplateTest.php

| **JIRA issue**     | [EZP-30166](https://jira.ez.no/browse/EZP-30166)
| **Target version** | 2.4?
| **Tests pass**     | no
The cause of the problem seems to be two things:
* In https://github.com/ezsystems/ezplatform-richtext/commit/23bd49b3797319f3ae2350ba1536dfd9a1e6dd31#diff-7310606d4fef503a40dee782da35ae00R210 we create a DOM document with multiple root notes
* DOMXPath seems to only take namespace definitions from the first parent element, and use the same ones on any other root elements. 
So in https://github.com/ezsystems/ezplatform-richtext/blob/master/src/lib/eZ/RichText/Converter/Link.php#L67, if the …

EZP-30166 :  RichText Link converter emits warning during custom tag conversion

---

src/bundle/DependencyInjection/Configuration.php

| **JIRA issue**     | [EZP-30386](https://jira.ez.no/browse/EZP-30386)
Provides configs for custom buttons in Alloy Editor. Example configuration:
```
ezrichtext:
alloy_editor:
extra_buttons:
toolbar1: [button1, button2]
paragraph: [random]
```
**TODO**:

EZP-30386: [Alloy Editor] Custom Buttons

---

src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/031-ezstyle.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/031-ezstyle.xml

| **JIRA issue**     | [EZP-29876](https://jira.ez.no/browse/EZP-29876)
| **Target version** | `1.0`
Note for QA: This bugfix depends on https://github.com/ezsystems/ezplatform-richtext/pull/32
**TODO**:

EZP-29876: New break lines disappear in Richtext while styled with custom styles

---

composer.json
tests/bundle/eZ/RichText/RendererTest.php
tests/lib/eZ/FieldType/RichText/RichTextStorageTest.php
tests/lib/eZ/REST/FieldTypeProcessor/RichTextProcessorTest.php
tests/lib/eZ/RichText/Converter/LinkTest.php
tests/lib/eZ/RichText/Converter/Render/EmbedTest.php
tests/lib/eZ/RichText/Converter/Render/TemplateTest.php

| **JIRA issue**     | n/a
| **Target version** | `1.0`, `1.1`, `master`
It seems that php-cs-fixer does not follow semver at all, so let's lock it at `2.15.x` to avoid fixing config or codebase on its every minor release.
At the same time I've decided that the new rule `php_unit_mock_short_will_return` is useful, so applied it along.
**TODO**:

[CS] Locked php-cs-fixer at v2.15.x and aligned codebase

---

src/lib/eZ/FieldType/RichText/Type.php

| **JIRA issue**     | [EZP-30626](https://jira.ez.no/browse/EZP-30626)
| **Improvement**| no
| **Doc needed**     |no
This PR adjust FieldType::getName() arguments to be compatible with `eZ\Publish\Core\FieldType\FieldType`
Related to: [https://github.com/ezsystems/ezpublish-kernel/pull/2661](https://github.com/ezsystems/ezpublish-kernel/pull/2661)
**TODO**:

EZP-30626: Change FieldType::getName() arguments

---

src/bundle/DependencyInjection/Configuration/Parser/FieldType/RichText.php
src/bundle/DependencyInjection/EzPlatformRichTextExtension.php
src/bundle/Resources/config/translation.yml
src/bundle/Resources/views/RichText/embed/content.html.twig
src/bundle/Resources/views/RichText/embed/content_inline.html.twig
src/bundle/Resources/views/RichText/embed/location.html.twig
src/bundle/Resources/views/RichText/embed/location_inline.html.twig
src/lib/Translation/Extractor/OnlineEditorCustomAttributesExtractor.php
src/lib/eZ/RichText/Converter/Render/Embed.php
src/lib/eZ/RichText/Resources/schemas/docbook/ezpublish.rng
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
tests/bundle/DependencyInjection/Configuration/Parser/FieldType/RichTextTest.php
tests/lib/eZ/RichText/Converter/Render/EmbedTest.php
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/008-orderedList.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/022-embed.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/023-embedInline.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/035-itemizedListWithNestedElements.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/008-orderedList.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/009-itemizedList.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/022-embed.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/023-embedInline.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/035-itemizedListWithNestedElements.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/008-orderedList.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/009-itemizedList.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/023-embedInline.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/035-itemizedListWithNestedElements.xml

| **JIRA issue**     | [EZP-29301](https://jira.ez.no/browse/EZP-29301)
| **Required by** | ezsystems/ezplatform-admin-ui#996
| **Requires** | ezsystems/ezpublish-kernel#2665
| **Target version** | `1.1.2` for eZ Platform `2.5.2`
This PR provides SiteAccess-aware semantic configuration for custom classes and attributes of RichText elements. AlloyEditor integration is provided via ezsystems/ezplatform-admin-ui#996
A sample configuration is as follows:
```yaml
ezpublish:
system:
<scope>: # e.g. default or admin_group
fieldtypes:
ezrichtext:
classes:
paragraph:
choices: ['class1', 'class2'] …
```

EZP-29301: Provided support for custom classes and data attributes

---

src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/032-ezstyleinline.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/032-ezstyleinline.xml

| **JIRA issue**     | [EZP-30628](https://jira.ez.no/browse/EZP-30628)
Soft return placed in the text wrapped with custom style isn't preserved after switching to edit mode. Related to https://github.com/ezsystems/ezplatform-richtext/pull/34 (proper rendering in view mode).
**TODO**:

EZP-30628: Soft return inside inline style is removed after edit

---

src/bundle/DependencyInjection/Compiler/RichTextHtml5ConverterPass.php
src/bundle/Resources/config/fieldtype_services.yaml
src/lib/eZ/FieldType/RichText/Type.php
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/fragment.xsl
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/xhtml5.xsl
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/output/fragment.xsl
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/output/xhtml5.xsl
src/lib/eZ/settings/fieldtype_services.yaml
tests/bundle/DependencyInjection/Compiler/RichTextHtml5ConverterPassTest.php
tests/bundle/DependencyInjection/EzPlatformRichTextExtensionTest.php
tests/integration/eZ/API/SetupFactory/RichTextSetupFactoryTrait.php
tests/lib/eZ/Persistence/Legacy/RichTextFieldValueConverterTest.php
tests/lib/eZ/settings/common.yaml

| **JIRA issue**     | [EZP-30517](https://jira.ez.no/browse/EZP-30517), [EZP-28009](https://jira.ez.no/browse/EZP-28009)
| **Required by** | ezsystems/ezpublish-kernel#2659
| **Target version** | `master (2.0@dev)` for eZ Platform `v3.0`
**This is a cumulative PR to be merged in a fast-forward way.**
This PR contains left-over fixes for obsolete parts of code related to [EZP-30517](https://jira.ez.no/browse/EZP-30517) and [EZP-28009](https://jira.ez.no/browse/EZP-28009):
- `ezpublish.ezrichtext.converter.output.xhtml5` becomes `ezrichtext.converter.output.xhtml5`,
- …

Fixed issues related to Kernel RichText code drop

---

src/bundle/Resources/views/RichText/style/default.html.twig
src/bundle/Resources/views/RichText/style/default_inline.html.twig

| **JIRA issue**     | [EZP-30814](https://jira.ez.no/browse/EZP-30814)
Continuation of https://github.com/ezsystems/ezpublish-kernel/pull/2708: replaced `spaceless` tag usages in favour of `spaceless` filter
**TODO**:

EZP-30814: Removed Twig deprecations

---

composer.json

| **JIRA issue**     | n/a
| **Tests pass**     | no
Tests in https://github.com/ezsystems/ezplatform-richtext/pull/53 are failing (example: https://travis-ci.org/ezsystems/ezplatform-richtext/jobs/569217334) with error:
```
1) EzSystems\IntegrationTests\EzPlatformRichText\eZ\API\RichTextFieldTypeIntegrationTest::testFromHash with data set #0 (array('<?xml version="1.0" encoding=...ion>\n'))
Cannot create a repository with predefined user. Check the UserService or RoleService implementation. 
Exception: Symfony\Component\Config\Exception\FileLocatorFileNotFoundException: The file …
```

[Composer] Added direct ezsystems/doctrine-dbal-schema dependency

---

src/bundle/Resources/config/templating.yaml
src/bundle/Templating/Twig/Extension/RichTextConverterExtension.php

| **JIRA issue**     | Discovered when working on [EZP-30393](https://jira.ez.no/browse/EZP-30393)
| **Target version** | `master (2.0)` for eZ Platform `v3.0`
| **BC breaks**      | no[1]
| **Doc needed**     | no[1]
In order to prepare for separated responsibilities for each Twig extension (one more is comming with 
[EZP-30393](https://jira.ez.no/browse/EZP-30393)) this PR renames Twig `RichTextExtension` to `RichTextConverterExtension`.
It also introduces some refactoring aligning code style and naming conventions.
[1] End-developer was never supposed to inject `EzSystems\EzPlatformRichTextBundle\Templating\Twig\Extension\RichTextExtensi …

[Twig] Renamed RichTextExtension to RichTextConverterExtension

---

src/lib/eZ/RichText/Converter/Render/Template.php
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
tests/lib/eZ/RichText/Converter/Render/TemplateTest.php
tests/lib/eZ/RichText/Converter/Render/_fixtures/template/input/08-line-breaks.xml
tests/lib/eZ/RichText/Converter/Render/_fixtures/template/output/08-line-breaks.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/031-ezstyle.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/031-ezstyle.xml

| **JIRA issue**     | [EZP-30730](https://jira.ez.no/browse/EZP-30730)
| **Target version** | `v1.1.4` for eZ Platform `v2.5.4 LTS`
This PR narrows down the scope of applied transformation rendering HTML `<br>` tags for nested Custom Templates (Tags/Styles) content to `docbook:literallayout` contents.
The issue is that at the moment of applying transformation of `docbook:ezcontent`, for the sample Custom Style:
```xml
<eztemplate name="style3" type="style">
<ezcontent>Line
break
</ezcontent>
</eztemplate>
```
the processed on the fly XML has the form of:
```xml
<?xml version="1.0"?>\n …
```

EZP-30730: Narrowed "LF to <br>" XSLT to literallayout scope

---

src/bundle/DependencyInjection/Configuration.php

| **JIRA issue**     | [EZP-30791](https://jira.ez.no/browse/EZP-30791)
| **Target version** | `1.1`
Create a new `custom-tag-test` custom tag and enable it (following [this steps](https://doc.ezplatform.com/en/latest/guide/extending_online_editor/#custom-tags)).
Expected result: new custom tag is added to online editor
Actual result: error message about missing custom tag declaration.
**TODO**:

EZP-30791: allow dashes in custom tag names

---

src/bundle/Resources/config/templating.yaml

| **JIRA issue**     | Follow-up to [EZP-30798](https://jira.ez.no/browse/EZP-30798)
| **Target version** | master for eZ Platform `v3.0`
With Symfony DIC auto-configuration enabled, explicit tagging of Twig extensions is not needed.
**TODO**:

EZP-30798: Simplified DIC of Twig YoutubeIdExtractorExtension

---

src/lib/eZ/RichText/Converter/Render.php
src/lib/eZ/RichText/Converter/Render/Template.php
tests/lib/eZ/RichText/Converter/Render/EmbedTest.php

| **JIRA issue**     | [EZP-30631](https://jira.ez.no/browse/EZP-30631)
| **Target version** | latest stable
Right now `getElementsByTagName` is used to fetch element's `ezconfig`. This kind config is used in different cases:
- custom attributes
- embed/custom tags parameters
Right now strange results sometimes are shown In cases when there are multiple nested elements with `ezconfig`. It happens because `getElementsByTagName` returns random (first?) `ezconfig` element. Instead, the first level child `ezconfig` should be returned. This PR fixes it.
1. Setup 2 custom tags: *custom_a* and …

EZP-30631: Fixed retrieving configuration (ezconfig) from DocBook tag

---

src/bundle/Resources/config/default_settings.yaml
src/bundle/Resources/config/fieldtype_services.yaml
src/bundle/Resources/views/RichText/content_fields.html.twig
src/bundle/eZ/RichText/Renderer.php
tests/bundle/DependencyInjection/Configuration/Parser/FieldType/RichTextTest.php
tests/bundle/eZ/RichText/RendererTest.php

| **JIRA issue**     | [EZP-30906](https://jira.ez.no/browse/EZP-30906)
main PR:
https://github.com/ezsystems/ezplatform/pull/453
**TODO**:

EZP-30906: Removed deprecated templating component integration

---

tests/integration/eZ/API/RichTextFieldTypeIntegrationTest.php

| **JIRA issue**     | [EZP-30934](https://jira.ez.no/browse/EZP-30934)
**TODO**:

EZP-30934: Removed usage of deprecated getCurrentUser method

---

bin/.travis/prepare_unittest.sh

| **JIRA issue**     | n/a, see: https://github.com/ezsystems/ezplatform-solr-search-engine/pull/152
To quote from https://github.com/ezsystems/ezplatform-solr-search-engine/pull/152:
> Due to the major changes in Solr, support for 7.X will be part of the ezplatform-solr-search-engine 2.0 release which will be compatible with eZ Platform 2.5 release. Solr 6.X will be dropped in this release.
> Solr 7.X and Solr 8.X will be officialy supported in ezplatform-solr-search-engine 3.0 release which will be compatible with eZ Platform 3.X.

[Travis] Bumped solr version in tests to 3.0

---

.travis.yml

| **JIRA issue**     | n/a
Failing build: https://travis-ci.org/ezsystems/ezplatform-richtext/jobs/594964777
Error:
```
Version '6.4.2' is not supported or not valid
```
This is the same solution as in https://github.com/ezsystems/ezpublish-kernel/pull/2802

[Travis] Updated Solr version in test matrix

---

src/bundle/DependencyInjection/Configuration.php
tests/bundle/DependencyInjection/Configuration/ConfigurationTest.php
tests/bundle/DependencyInjection/Fixtures/custom_tags/input/000-attribute-type-number.yaml
tests/bundle/DependencyInjection/Fixtures/custom_tags/input/001-attribute-type-string.yaml
tests/bundle/DependencyInjection/Fixtures/custom_tags/input/002-attribute-type-boolean.yaml
tests/bundle/DependencyInjection/Fixtures/custom_tags/input/003-attribute-type-choice.yaml
tests/bundle/DependencyInjection/Fixtures/custom_tags/input/004-attribute-type-link.yaml
tests/bundle/DependencyInjection/Fixtures/custom_tags/output/000-attribute-type-number.yaml
tests/bundle/DependencyInjection/Fixtures/custom_tags/output/001-attribute-type-string.yaml
tests/bundle/DependencyInjection/Fixtures/custom_tags/output/002-attribute-type-boolean.yaml
tests/bundle/DependencyInjection/Fixtures/custom_tags/output/003-attribute-type-choice.yaml
tests/bundle/DependencyInjection/Fixtures/custom_tags/output/004-attribute-type-link.yaml

| **JIRA issue**     | [EZP-30933](https://jira.ez.no/browse/EZP-30933)
| **Requires** | ezsystems/ezplatform-admin-ui#1112
| **Target version** | `1.1` for eZ Platform `v2.5.x` LTS
| **Tests pass**     | [yes](https://travis-ci.org/ezsystems/ezplatform-richtext/builds/602236414)
**Note: _Inability to migrate from `ezxmltext` to `ezrichtext` due to input field validation error is considered here as a bug, nothing more._**
This PR provides a minimal support for the Custom Tag `link` attribute type. That attribute type can be configured in the following way:
``` yaml
ezrichtext:
custom_tags:
<tag_name>:
link:
type: …
```

EZP-30933: Added "link" Custom Tag attribute type

---

src/bundle/eZ/RichText/Renderer.php
tests/bundle/eZ/RichText/RendererTest.php

| **JIRA issue**     | [EZP-31076](https://jira.ez.no/browse/EZP-31076)
| **Bug**| yes
| **Target version** | `1.1`/`master`
As mentioned in the JIRA ticket, currently embedded content is displayed even if it's hidden. This PR fixes this incorrect behavior. 
**TODO**:

EZP-31076: Skipped rendering hidden embedded content

---

.php_cs
composer.json
src/bundle/eZ/RichText/Renderer.php
src/lib/eZ/RichText/Converter/Render/Embed.php
src/lib/eZ/RichText/ConverterDispatcher.php
src/lib/eZ/RichText/XmlBase.php

| **JIRA issue**     | [EZP-31108](https://jira.ez.no/browse/EZP-31108)
| **Target version** | `v1.1.x` and up (of this package)
This PR enables the [ezsystems/ezplatform-code-style](https://github.com/ezsystems/ezplatform-code-style) package, in order to use common rules defined via ezsystems/ezplatform-code-style#3.
**TODO**:

EZP-31108: [CS] Enabled ezsystems/ezplatform-code-style package

---

src/lib/eZ/RichText/Converter/Render/Template.php
tests/lib/eZ/RichText/Converter/Render/TemplateTest.php
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/024-template.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/025-templateInline.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/034-nestedTemplate.xml

| **JIRA issue**     | [EZP-31130](https://jira.ez.no/browse/EZP-31130)
| **Target version** | `v1.1.x` for eZ Platform `2.5.x` LTS
| **Doc needed**     | no, doc is already aligned
This PR introduces small change - ensuring that `content` Twig variable is always present in Custom Template (Tag, Style) Twig view.
eZ Platform DocBook schema (`.rng`) currently allows `ezcontent` tag to be not present in `eztemplate`. While AdminUI ensures `ezcontent` is always set, even if empty, a DocBook comming from migrated `XmlText` might not have this tag sometimes. This resulted in `content` Twig variable being not present in …

EZP-31130: Ensured content variable is always present in Custom Template Twig view

---

composer.json
src/bundle/DependencyInjection/Configuration.php
tests/bundle/DependencyInjection/Configuration/ConfigurationTest.php

| **JIRA issue**     | [EZP-31087](https://jira.ez.no/browse/EZP-31087)
**Steps to reproduce**
1. Install/enable the first bundle, which provides an additional button in Online Editor, f.e. [ezplatform-content-variables](https://ezplatform.com/packages/contextualcode-ezplatform-content-variables). And check that the "Content Variables" button is injected into the OE.
2. Install/enabled the second bundle, which also provides an additional button in Online Editor, f.e. [ezplatform-alloyeditor-source](https://ezplatform.com/packages/contextualcode-ezplatform-alloyed …

EZP-31087: Fixed merging Online Editor extra_buttons semantic config

---

tests/integration/eZ/API/SetupFactory/CoreSetupFactoryTrait.php

| **JIRA issue**     | [EZP-30882](https://jira.ez.no/browse/EZP-30882)
| **Bug/Improvement**| fix failing tests
| **Tests pass**     | should
Tests are currently failing on master: https://travis-ci.org/ezsystems/ezplatform-richtext/builds/633634372?utm_source=slack&utm_medium=notification with an error:
```
Exception: Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "ezpublish.api.inner_repository" has a dependency on a non-existent service "eZ\Publish\Core\Repository\Strategy\ContentThumbnail\ThumbnailChainStrategy". in …
```

EZP-30882: Added loading thumbnails to CoreSetupFactoryTrait

---

src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-image-link.js

| **JIRA issue**     | [EZP-31245](https://jira.ez.no/browse/EZP-31245)
The solution from admin-UI PR https://github.com/ezsystems/ezplatform-admin-ui/pull/1179.
PR for eZ Platform  3.0
**TODO**:

EZP-31245: Editing link in paragraph containing more lines ends up with JS error

---

src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/003-inlinestyles.docbook.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/003-inlinestyles.xhtml5.edit.xml

| **JIRA issue**     | [EZP-30129](https://jira.ez.no/browse/EZP-30129)
| **Target version** | 1.1 (2.5)
Format coming from copy /paste will often use `<b>` and `<i>` tags, or sometimes also span tags with bold / italic style attribute. This change makes sure to map these cases to the correct docbook tags we support. Solving the linked Word copy / paste issue, as well as improving the code for import use cases from other systems.
**TODO**:

EZP-30129: Handled bold & italic styles when converting from OE format to DocBook

---

src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/006-paragraph.docbook.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/006-paragraph.xhtml5.edit.xml

| **JIRA issue**     | [EZP-30130](https://jira.ez.no/browse/EZP-30130)
| **Target version** | 1.1, master
As we allow having soft breaks within clean paragraphs and we flush inline tags, we can also avoid validation crashes by checking line breaks inside nested `<span>` tags coming from external editors like Word. Behavior is the same as with `<p>text[soft_break]more text</p>` formatting.
**TODO**:

EZP-30130: Added handling of soft breaks inside nested formatting within paragraphs

---

src/lib/eZ/FieldType/RichText/SearchField.php
src/lib/eZ/FieldType/RichText/Type.php
src/lib/eZ/Persistence/Legacy/RichTextFieldValueConverter.php

| **JIRA issue**     | [EZP-29984](https://jira.ez.no/browse/EZP-29984) & [EZP-29958](https://jira.ez.no/browse/EZP-29958)
| **Target version** | 1.1+
| **Tests pass**     | yes?
| **Doc needed**     | no?
Ports over fixes from:
- EZP-29984: Fix LIKE support for * as wildcard across engines, deprecate % usage
- https://github.com/ezsystems/ezpublish-kernel/pull/2517
Which also happens to align RichText with how XmlText had been fixed for:
- "Creating paragraph longer than 32766 bytes in RichText Editor will fail with Solr Error"
- https://jira.ez.no/browse/EZP-29958
**TODO**:

Ported fix for EZP-29958 and EZP-29984 from kernel

---

src/bundle/Resources/encore/ez.config.js
src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-styleslistitem.js

| **JIRA issue**     | [EZEE-2914](https://jira.ez.no/browse/EZEE-2914)
| **Target version** | master target 3.0
AlloyEditor.ButtonStylesListItem on click does not update textarea element, because function _onClick is protected and we cannot override, so we need an override render function, for add a new function into onClick in order to update textarea
**TODO**:

EZEE-2914: Custom inline style does not update textarea after click on

---

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-attributes-update.js

| **JIRA issue**     | [EZP-31295](https://jira.ez.no/browse/EZP-31295)
**TODO**:

EZP-31295: Unable to use default empty custom CSS class in the OE

---

src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/023-embedInline.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/035-itemizedListWithNestedElements.xml

| **JIRA issue**     | [EZP-31321](https://jira.ez.no/browse/EZP-31321), related to [EZP-29882](https://jira.ez.no/browse/EZP-29882)
| **Required by** | ezsystems/ezplatform-admin-ui#1151
The original fix for this issue was https://github.com/ezsystems/ezplatform-admin-ui/pull/746. Which fixed the symptoms, but introduced zero-width spaces. Which are causing serious issues in 
https://github.com/ezsystems/ezplatform-admin-ui/pull/1034, and seems to be a nice reason for some very strange bugs in the future.
Before posting this PR, we checked the original issue to …

EZP-31321: Replaced zero-width space with oe-upcast-placeholder

---

src/bundle/Resources/public/js/OnlineEditor/plugins/ez-custom-tag.js
src/bundle/Resources/public/js/OnlineEditor/plugins/ez-embed.js

| **JIRA issue**     | [EZP-31321](https://jira.ez.no/browse/EZP-31321)
**TODO**:

EZP-31321: Dropped injecting zero-width space into ezembed(inline) elements

---

tests/integration/eZ/API/SetupFactory/CoreSetupFactoryTrait.php

| **JIRA issue**     | [EZP-31278](https://jira.ez.no/browse/EZP-31278)
| **Target version** | `master` for eZ Platform `v3.0`
This PR removes the usage of the RegisterLimitationTypePass which has been dropped via ezsystems/ezpublish-kernel#2914.
Affects test setup only, so if passes, can be merged as-is.
**TODO**:

EZP-31278: Removed usage of the obsolete RegisterLimitationTypePass

---

src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/007-table.docbook.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/007-table.xhtml5.edit.xml

| **JIRA issue**     | [EZP-30222](https://jira.ez.no/browse/EZP-30222)
| **Target version** | 1.1, master
This PR  introduces a slightly different way of handling table width:
- introducing `normalizeWidth` function which handles `px` and `pt` units as these are the main ones used in tables,
- rounding width values, e.g. `110.5pt`,
- taking `style="border: [thickness] [style] [color];"` property from CSS into account and applying `border="1px"` to make things consistent with the tables generated by RTE by default.
**TODO**:

EZP-30222: Handled tables copied from external sources

---

src/bundle/Resources/translations/online_editor.en.xlf

| **JIRA issue**     | [EZP-31293](https://jira.ez.no/browse/EZP-31293)
1. Setup some custom CSS classes, for example:
```
system:
default:
fieldtypes:
ezrichtext:
classes:
paragraph:
choices: [custom-paragraph-1, custom-paragraph-2, custom-paragraph-3]
default_value: custom-paragraph-1
required: false
multiple: false {code}
```
2. Open Online Editor and try to set a custom CSS class for a paragraph
The text label for custom classes will be shown.
*ezrichtext.classes.class.label* is shown, instead of text label.
**TODO**:

EZP-31293: Defined UI translation label for the custom CSS classes

---

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-styleslistitem.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-custom-style.js

| **JIRA issue**     | [EZP-31137](https://jira.ez.no/browse/EZP-31137)
| **Doc needed**     |no
ez-custom-style.js for alloy editor was overriding base config styles by filtering out default styles unnecessarily if custom styles were in use.
**TODO**:

EZP-31137: Fixed styles dropdown when custom ones are in use for RTE

---

src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/008-anchor.docbook.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/008-anchor.xhtml5.edit.xml

| **JIRA issue**     | [EZP-31272](https://jira.ez.no/browse/EZP-31272)
| **Target version** | 1.1, master
Currently, anchors pasted from external sources often contain `name` attribute: `<a name="test">`. Since we only support `id` attribute I decided to add a simple mapping that prevents RTE validation from crushing.
**TODO**:

EZP-31272: Handled anchors generated with name attribute

---

src/bundle/Resources/public/js/OnlineEditor/toolbars/config/base-table.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-table-cell.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-table-header.js

| **JIRA issue**     | [EZP-31380](https://jira.ez.no/browse/EZP-31380)
https://github.com/ezsystems/ezplatform-admin-ui/pull/1232
**TODO**:

EZP-31380: Disable manage rows/cells buttons for table and row toolbars

---

src/bundle/Resources/encore/ez.config.js
src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-dropdown.js
src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-styleslist.js

| **JIRA issue**     | [EZP-31356](https://jira.ez.no/browse/EZP-31356)
| **Bug**| yes
| **Doc needed**     |no
The focus event which is hardcoded into the AlloyEditor and attached to the styles dropdown list is not working correctly on Firefox and Safari. The reasoning for the solution was to implement `ButtonDropdown` component without this `focus` event, which does more harm than good and inject it into newly created `EzButtonStylesList` component which overwrites the default AlloyEditor's `ButtonStylesList` in order to prevent other components of being mutated.
**TODO**:

EZP-31356: Fixed styles dropdown selection on Firefox and Safari

---

src/bundle/eZ/RichText/Renderer.php

| **JIRA issue**     | [EZP-31118](https://jira.ez.no/browse/EZP-31118)
| **Target version** |  `master`
Fixed issues reported in ezsystems/ezpublish-kernel#2866 (review):
```
Argument 1 passed to eZ\Publish\Core\Repository\ContentService::loadContent() must be of the type int, string given, called in /home/vagrant/master/vendor/ezsystems/ezplatform-richtext/src/bundle/eZ/RichText/Renderer.php on line 130
```
**TODO**:

EZP-31118: Introduced strict types for ContenteService

---

src/lib/eZ/RichText/Converter/Link.php

| **JIRA issue**     | [EZP-31118](https://jira.ez.no/browse/EZP-31118)
Fixed failing Travis build:
https://travis-ci.org/github/ezsystems/ezplatform-richtext/jobs/662976234. 
ID's extracted by regexp form internal URL should be cased to int in `EzSystems\EzPlatformRichText\eZ\RichText\Converter\Link::convert`
Note for reviewers: in the near future this logic will be completly refactored as part of the https://github.com/ezsystems/ezplatform-richtext/pull/112
**TODO**:

EZP-31118: Added missing int casting in the Converter\Link::convert

---

src/lib/eZ/RichText/Converter/Render/Embed.php

Fixes `Uncaught Error: Argument 1 passed to eZ\Publish\Core\Repository\SiteAccessAware\ContentService::loadContent() must be of the type int, string given, called in /var/www/vendor/ezsystems/ezplatform-richtext/src/bundle/eZ/RichText/Renderer.php on line 130`
I've changed regexp to be more strict by validating identifiers as integers only. Int casting is also required due to strict types introduced in Repository.

Fixed passing strict ID parameters when processing embed

---

src/bundle/Resources/public/js/OnlineEditor/core/base-richtext.js

| **JIRA issue**     | [EZEE-3030](https://jira.ez.no/browse/EZEE-3030)
This is a followup for https://github.com/ezsystems/ezplatform-admin-ui/pull/1283 targeting eZ Platform 3.0 (`master`).
**TODO**:

EZEE-3030: Links containing 'ezlocation` or 'ezcontent' keywords break RTE validation on paste

---

README.md
composer.json
tests/integration/eZ/API/SetupFactory/CoreSetupFactoryTrait.php

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-31007](https://jira.ez.no/browse/EZP-31007)
| **Type**                                   | improvement
| **Target eZ Platform version** | `v3.0.0`
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no
This PR replaces `ezpublish-kernel` with `ezplatform-kernel` and fixes dependency issues blocking package installation (due to Composer minimum stability requirements):
- `ezsystems/doctrine-dbal-schema:^1.0@dev` is required  by `ezplatform-kernel:^1.0@dev`
- other packages are required by `ezsystems/ezplatform-admin-ui:^2.0@dev`

EZP-31007: Replaced ezpublish-kernel with ezplatform-kernel

---

src/bundle/DependencyInjection/Configuration/Parser/FieldType/RichText.php
src/bundle/Resources/config/prepend/ezpublish.yaml
src/bundle/Resources/public/js/OnlineEditor/core/base-richtext.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/base-buttons.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/base-list.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/base-table.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/base.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-custom-style.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-custom-tag.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-embed-inline.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-embed.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-formatted.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-heading.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-image-link.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-image.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-inline-custom-tag.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-link.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-paragraph.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-table-cell.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-text.js
src/lib/Configuration/Provider/AlloyEditor.php
tests/lib/Configuration/Provider/AlloyEditorTest.php

| **JIRA issue**     | [EZP-30545](https://jira.ez.no/browse/EZP-30545)
Example configuration:
```yaml
system:
admin_group:
fieldtypes:
ezrichtext:
toolbars:
my_toolbar:
buttons:
my_last_button:
priority: -100
hidden_button:
visible: false
first_button:
priority: 50
button_with_defaults:
priority: 0
visible: true
```
**For QA**
All toolbars should be in the same place and with the same buttons by default
We need to test if it is possible to change the order of buttons in toolbars (by priority) and hide some buttons (by visible), also we need to test if …

EZP-30545: Provided way to define buttons in AlloyEditor toolbars

---

src/lib/eZ/RichText/Converter/Link.php
tests/lib/eZ/RichText/Converter/AggregateTest.php
tests/lib/eZ/RichText/Converter/LinkTest.php

| **JIRA issue**     | Follow-up to [EZP-31499](https://jira.ez.no/browse/EZP-31499) and
| **Target version** | `master` for eZ Platform 3.0
Due to changes via ezsystems/ezpublish-kernel#3000 `UrlAliasRouter::generate` follows now `\Symfony\Component\Routing\Generator\UrlGeneratorInterface` prototype and does not accept `Location` directly
**TODO**:

EZP-31499: Fixed generating routes for links in DocBook

---

.travis.yml
src/lib/eZ/FieldType/RichText/SearchField.php
tests/lib/eZ/FieldType/RichText/SearchFieldTest.php

| **JIRA issue**     | [EZP-31512](https://jira.ez.no/browse/EZP-31512)
| **Target version** | `1.1.x` for eZ Platform 2.5.x LTS
| **Tests pass**     | [yes](https://travis-ci.org/github/ezsystems/ezplatform-richtext/builds/666501464)
This is a port of ezsystems/ezpublish-kernel#3008, see description there for all the details.
This PR actually fixes issue with production code.
I've also added Travis job for unit tests on PHP 7.3.
**TODO**:
- ~Ask for Code Review.~ review in ezsystems/ezpublish-kernel#3008

EZP-31512: Fixed extracting Search Fields from RichText

---

composer.json
src/lib/eZ/FieldType/RichText/RichTextStorage.php
src/lib/eZ/FieldType/RichText/RichTextStorage/Gateway.php
tests/integration/eZ/API/RichTextFieldTypeIntegrationTest.php
tests/lib/eZ/FieldType/RichText/RichTextStorageTest.php

| **JIRA issue**     | [EZP-31129](https://jira.ez.no/browse/EZP-31129)
| **Requires** | ezsystems/ezpublish-kernel#2957
Depends on: https://github.com/ezsystems/ezpublish-kernel/pull/2957
When editing ContentType from RichText which has links. In the link manager,  links are still there from the previous version, because when creating a draft, the links from the current version are moved to the new version and when saving there is no verification which links exist and which ones do not, therefore when saving data from RichText, the removal of links from the …

EZP-31129: Removed outdated URLs when storing Field data

---

tests/integration/eZ/SPI/RichTextFieldTypeIntegrationTest.php
tests/lib/eZ/FieldType/RichText/Gateway/DoctrineStorageTest.php

| **JIRA issue**     | [EZP-31246](https://jira.ez.no/browse/EZP-31246)
| **Target version** | `master` (package internal test setup)
This PR replaces 2 remaining usages of Zeta Components Database Handler from tests.
**TODO**:

EZP-31246: [Tests] Refactored tests not to rely on eZc Database

---

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-tableremove.js

| **JIRA issue**     | [EZP-30940](https://jira.ez.no/browse/EZP-30940)
This is a followup for https://github.com/ezsystems/ezplatform-admin-ui/pull/1321 targeting 3.0.
**TODO**:

EZP-30940: Cannot remove table from richtext field

---

src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/008-orderedList.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/009-itemizedList.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/010-htmlInformaltable.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/008-orderedList.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/009-itemizedList.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/004-itemizedList.docbook.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/004-itemizedList.xhtml5.edit.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/005-orderedList.docbook.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/005-orderedList.xhtml5.edit.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/008-orderedList.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/009-itemizedList.xml

| **JIRA issue**     | [EZP-29196](https://jira.ez.no/browse/EZP-29196)
| **Target version** | `1.1` and `master`
Currently, DocBook schema for ordered/itemized list doesn't contain proper handling of paragraphs that results in not reflecting break lines. The idea is to reuse an already implemented rule for paragraph (`ezxhtml5:p`).
**TODO**:

EZP-29196: Handled line breaks inside itemized/ordered lists

---

src/lib/eZ/RichText/RelationProcessor.php
tests/lib/eZ/RichText/RelationProcessorTest.php

| **JIRA issue**     | [EZEE-3094](https://jira.ez.no/browse/EZEE-3094)
**TODO**:

EZEE-3094: Added missing int casting in the RelationProcessor::getRelatedObjectIds

---

src/bundle/Resources/public/js/OnlineEditor/core/base-richtext.js

| **JIRA issue**     | [EZP-31539](https://jira.ez.no/browse/EZP-31539)
This is a followup for https://github.com/ezsystems/ezplatform-admin-ui/pull/1338 targeting 3.0.
**TODO**:

EZP-31539: Link Validation error in Richtext Editor

---

tests/integration/eZ/API/SetupFactory/CoreSetupFactoryTrait.php

| **JIRA issue**     | Follow up for [EZP-30465](https://jira.ez.no/browse/EZP-30465) introduced via ezsystems/ezplatform-kernel#44
| **Target version** | Test setup of eZ Platform v3.0.x
This is a follow-up aligning integration tests SetupFactory with changes from ezsystems/ezplatform-kernel#44. Config for `autowire.yml` was not loaded. 
Please note that this not very DRY solution needs to be changed, but here it's out of scope. The scope here is to unblock failing CI: https://travis-ci.org/github/ezsystems/ezplatform-richtext/builds/674730281.
**TODO**:

[Tests] Aligned SetupFactory to include PermissionService

---

src/bundle/Resources/config/ui/mappers.yaml
src/lib/Configuration/UI/Mapper/CustomTag.php
tests/lib/Configuration/UI/Mapper/CustomTagTest.php

| **JIRA issue**     | [EZP-31547](https://jira.ez.no/browse/EZP-31547)
| **Bug**| yes
Merge up for https://github.com/ezsystems/ezplatform-admin-ui/pull/1335

EZP-31547: Autowiring fails for CustomTag service when using 3rd party translator bundle

---

src/lib/eZ/RichText/Resources/schemas/docbook/docbook.rng
src/lib/eZ/RichText/Resources/schemas/docbook/ezpublish.rng
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/001-title.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/001-title.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/001-title.xml

| **JIRA issue**     | [EZP-30861](https://jira.ez.no/browse/EZP-30861)
| **Target version** | `1.1`, `2.0`, `master`
Currently, there is another inconsistent scenario when line breaks appear inside headings (`<h1> - <h6>`). As `literallayout` tag responsible for correctly displaying breaklines cannot be placed inside `<title>` tag (according to DocBook schema), I adjusted `docbook.rng` to reflect this case. As `db.all.inlines` rules are used in many places, I decided to add `literallayout` only to `title` element to avoid potential issues. XSL logic is basically about reusing existing …

EZP-30861: Handled line breaks inside headings

---

src/bundle/eZ/RichText/Renderer.php

| **JIRA issue**     | [EZP-31626](https://jira.ez.no/browse/EZP-31626)
| **Requires** | https://github.com/ezsystems/ezplatform-admin-ui/pull/1374
We faced this issue during upgrade to eZ Platform v3 from eZ Publish. And seems like the only `ezcontent://` links are used in eZ Platform v3 UI, which makes hard to reproduce it on the clean eZ Platform v3.0.3 installation.
**Steps to reproduce**
1. Create a new Article, and embed location in its RichText field. The simplest way is to use [https://gitlab.com/contextualcode/ezplatform-alloyeditor-source] and add the …

EZP-31626: Fixed rendering of embed locations

---

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-customtag-update.js

| **JIRA issue**     | [EZP-31612](https://jira.ez.no/browse/EZP-31612)
**Steps to reproduce:**
1. Create a custom tag with choices attribute:
```
custom_tags:
factbox:
template: '@ezdesign/custom_tag/factbox.html.twig'
icon: '/bundles/factbox/img/icons.svg'
is_inline: false
attributes:
options:
type: choice
choices:
- option1
- option2
default_value: option1
required: true
```
2. Create translations for choice labels:
```
ezrichtext.custom_tags.factbox.attributes.options.choices.option1.label: 'Option 1' …
```

EZP-31612: use custom tag choice labels

---

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-linkedit.js

| **JIRA issue**     | [EZP-31641](https://jira.ez.no/browse/EZP-31641)
**Steps to reproduce**
1. Open for editing any content with RichText field in Admin UI
2. Add an empty 3x3 table into the RichText field
3. Type "test" In the first table cell
4. Select typed text from the previous step, and make it link to "https://url.com"
**Expected results**
The cursor is moved to the next table cell and the toolbar for that cell is shown.
**Actual results**
The next table cell is selected, and the table cell toolbar is missing. The toolbar is not shown even if the user …

EZP-31641: Unable to manage links in table cells

---

composer.json
src/bundle/Resources/views/RichText/embed/content.html.twig
src/bundle/Resources/views/RichText/embed/content_denied.html.twig
src/bundle/Resources/views/RichText/embed/content_inline.html.twig
src/bundle/Resources/views/RichText/embed/content_inline_denied.html.twig
src/bundle/Resources/views/RichText/embed/location.html.twig
src/bundle/Resources/views/RichText/embed/location_denied.html.twig
src/bundle/Resources/views/RichText/embed/location_inline.html.twig
src/bundle/Resources/views/RichText/embed/location_inline_denied.html.twig

| **JIRA issue**     | [EZP-31673](https://jira.ez.no/browse/EZP-31673)
| **Bug**  | yes
| **Tests pass**     | yes/no
Update to use new cache functions.
**TODO**:

EZP-31673: RichText should use new http-cache 2.0

---

composer.json

Seems the Kernel version is quite outdated making RichText use latest release rather than stable 7.5

[Composer] Bumped Kernel version to ^7.5.11@dev to test on 7.5.x-dev

---

src/bundle/Resources/public/scss/_custom-tag.scss

| **JIRA issue**     | [EZP-30366](https://jira.ez.no/browse/EZP-30366)
Make custom tag blocks full-width in the Online Editor
**TODO**:

EZP-30366: Use full width for custom tags in Online Editor

---

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-linkedit.js

| **JIRA issue**     | [EZP-31933](https://jira.ez.no/browse/EZP-31933)
| **Target version** | `2.1`
**Steps to reproduce**
1. Open any RichText field in Online Editor
2. Remove all the field content
3. Insert any custom tag
4. Make sure there are no empty paragraphs before and after the inserted custom tag
5. Edit the custom tag
6. Insert a "test" text
7. Make the inserted text a link
8. Chose any location for the link
9. Click the "Save" link button
**Expected result**
The link within the custom tag is updated.
**Actual result**
The link is updated, but Online Editor breaks because of …

EZP-31933: Fixed custom tag link edit

---

src/lib/eZ/RichText/Converter/Render/Template.php
tests/lib/eZ/RichText/Converter/Render/TemplateTest.php
tests/lib/eZ/RichText/Converter/Render/_fixtures/template/input/04-block-nested-template.xml
tests/lib/eZ/RichText/Converter/Render/_fixtures/template/output/04-block-nested-template.xml

| **JIRA issue**     | [EZP-30887](https://jira.ez.no/browse/EZP-30887)
On the first `convert` iteration, `$templates` variable contains all the templates (including nested custom tags).
But, there will be a new call of `convert` in `getCustomTemplateContent` function, which leads to the same template processed multiple times.
Extra calls count equal to custom tag depth.
**TODO**:
P.S. Was found and fixed in related bundle https://gitlab.com/contextualcode/ezplatform-richtext-template-extension/commit/01bb8c75ff0be8470b7bc9e9c6b0e94e4c187c61
cc: @SerheyDolgushev

EZP-30887: Optimized processing Custom Tag templates

---

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-linkedit.js

| **JIRA issue**     | N/A
| **Target version** | 2.1
With this PR I want to clean up the mess created in https://github.com/ezsystems/ezplatform-richtext/pull/148. Per my understanding, the following happened:
1. https://github.com/ezsystems/ezplatform-richtext/pull/148 and https://github.com/ezsystems/ezplatform-richtext/pull/149 were submitted at the same time.
2. https://github.com/ezsystems/ezplatform-richtext/pull/149 was based on `2.0` and it was QAed and merged almost right after submission.
3. https://github.com/ezsystems/ezplatform-richtext/pull/148 was based on `master` and it …

Fixes #149 and #163

---

src/lib/eZ/RichText/Resources/schemas/ezxhtml5/output/ezxhtml5.xsd
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/007-table.docbook.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/007-table.xhtml5.edit.xml

| **JIRA issue**     | [EZP-31642](https://jira.ez.no/browse/EZP-31642)
| **Target version** | 2.1
This PR just extends DocBook schema, so it would match the definition set in `docbook.rng`:
> Specifies the width (in pixels only) of the frame around a table.
Please note, another PR to provide the UI is coming.
**TODO**:

EZP-31642: As an Editor I want be able to edit table borders

---

src/lib/eZ/FieldType/RichText/Type.php
tests/lib/eZ/FieldType/RichTextTest.php

| **JIRA issue**     | [EZP-31954](https://jira.ez.no/browse/EZP-31954)
| **Target version** | 1.0
This is a part of issue with RichText XML validation fails,  where fatal error displayed:
> Argument 2 passed to Symfony\Component\Validator\Util\PropertyPath::append() must be of the type string, null given, called in /app/vendor/ezsystems/ezplatform-content-forms/src/lib/Validator/Constraints/FieldValueValidator.php on line 92 [in vendor/symfony/validator/Util/PropertyPath.php:34]`
see https://github.com/ezsystems/ezplatform-content-forms/pull/34
I see similar is done for Float field type …

EZP-31954: add missed validation error target

---

src/lib/eZ/RichText/Converter/Render/Template.php
src/lib/eZ/RichText/Resources/schemas/docbook/ezpublish.rng
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/034-nestedTemplate.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/024-template.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/031-ezstyle.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/034-nestedTemplate.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/034-nestedTemplate.xml

| **JIRA issue**     | [EZP-31231](https://jira.ez.no/browse/EZP-31231)
| **Bug**| yes
Align and anchor attributes were not storing and displaying properly when working with custom style, also additional option to render `id` attribute has been added in form of:
```
<h2 id="{{ id }}" style="text-align:{{ align }}; color:red">
{{ content }}
</h2>
```
where the code above is some [custom style](https://doc.ezplatform.com/en/2.5/guide/extending/extending_online_editor/#custom-styles).
// maintainer update:
- Custom Tags and Styles share markup and codebase, so regressions should be checked …

EZP-31231: Fixed storing align and anchor attributes for custom styles

---

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-customtag-update.js

| **JIRA issue**     | [EZP-32187](https://issues.ibexa.co/browse/EZP-32187)
| **Target version** | 3.1, 3.2
**STR**:
On a clean install, edit any content with richtext field
Click "+" (Add) button on the left
Select "Facebook" tag (or any other)
Fill attributes and save
On the top bar, click "pencil" (edit) icon to edit custom tag attributes
Click "Cancel"
**AR**: Richtext fields editing unresponsive, error in console - "Cannot read property 'isAligned' of null"
**ER**: Attributes editing closed, and top bar displayed. The same as after "Save" button click.
**TODO**:

EZP-32187: Fix RichText unresponsive after cancel editing of custom tag attributes

---

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-linkedit.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/base-fixed.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/base-table.js
src/bundle/Resources/public/js/OnlineEditor/toolbars/config/base.js

| **JIRA issue**     | [EZP-31632](https://jira.ez.no/browse/EZP-31632)
Right now table toolbar has fixed positioning, and in some cases it brings inconvenience.
**Steps to reproduce:**
1. Open any content with RichtText field for editing
2. Insert a big table (50 rows) into RichText field
3. Scroll to the last table row and try to insert a new row after it
**Expected result**
The table toolbar should be shown on the screen, and new row should be inserted without any scrolling.
**Actual result**
The table toolbar remains at the start of the table. And the …

EZP-31632: Floating table toolbar

---

src/bundle/Resources/config/prepend/ezpublish.yaml

| **JIRA issue**     | [EZP-32194](https://jira.ez.no/browse/EZP-32194)
| **Target version** | 2.2
There is no reason to have an "embed-inline" button in the "table" and "table-row" toolbars.
**TODO**:

EZP-32194: Disable embed-inline for table/table-row toolbars

---

src/bundle/Resources/config/rest.yaml

| **JIRA issue**     | [EZP-32340](https://jira.ez.no/browse/EZP-32340)
| **Type**| improvement
| **Target version** | `3.2`+
Deprecated `ezpublish_rest.field_type_processor` in favour of `ezplatform.field_type.rest.processor`.
**TODO**:

EZP-32340: Deprecated ezpublish_rest.field_type_processor in favour of ibexa.rest.field_type.processor

---

src/bundle/Resources/public/js/OnlineEditor/plugins/base/ez-custom-tag-base.js

| **JIRA issue**     | [EZP-32351](https://jira.ez.no/browse/EZP-32351)
| **Target version** | `2.2`, `master`
>In custom tags, there are no icons for switch between attributes and content.
**TODO**:

EZP-32351: Custom tags' switch between attributes and content is missing an icon

---

src/bundle/Resources/public/js/OnlineEditor/core/base-richtext.js

| **JIRA issue**     | [EZP-32400](https://jira.ez.no/browse/EZP-32400)
| **Target version** | `2.2`, `2.3`, `master`
Followup for https://github.com/ezsystems/ezplatform-admin-ui/pull/1745 targetting v3. Here, there is also a fix for the wrong anchor icon rendering.
**TODO**:

EZP-32400: Fixed displaying anchors for tables

---

src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/014-link.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/014-link.xml
tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/014-link.xml

| **JIRA issue**     | [IBX-284](https://issues.ibexa.co/browse/IBX-284)
| **Target version** | `1.1`, `2.2`, `2.3`, `master`
Soft line breaks are not properly interpreted when inserted in links. This PR aims to add proper usage of `breakline` template, as in other cases.
**TODO**:

IBX-284: Fixed line breaks inside links

---

src/bundle/Templating/Twig/Extension/RichTextConverterExtension.php

| **JIRA issue**     | [IBX-707](https://issues.ibexa.co/browse/IBX-707)
| **Target version** | `2.3`, `master`
Given `saveHTML` method might return false in case of external errors/libxml flaws, we should introduce more bulletproof checks for returned values. Error logging doesn't seem to be needed, as the converter will throw an exception in case of any libxml errors anyway, ref: https://github.com/ezsystems/ezplatform-richtext/blob/68e21b4be1477c09bb1a5cf0e2a9fae648a42b69/src/lib/eZ/RichText/Converter/Xslt.php#L140
**TODO**:

IBX-707: Improved RichTextConverterExtension libxml-related error handling

---

src/bundle/Resources/public/js/OnlineEditor/toolbars/config/base.js

| **JIRA issue**     | [IBX-759](https://issues.ibexa.co/browse/IBX-759)
| **Target version** | `2.3`, `master`
Currently, there is a wrong class specified when calculating the toolbar's width. That results in JS errors when it changes. Went for `.ae-toolbar-styles` as it seems to be a generic class shared between all the affected toolbars.
**TODO**:

IBX-759: Fixed wrong class taken to calculate toolbar's width

---

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-customtag-update.js

| **JIRA issue**     | [IBX-962](https://jira.ez.no/browse/IBX-962)
| **Target version** | `2.3`
**Steps to reproduce:**
1. Create a new content item with RichText field
2. Try to insert Facebook (or any other) custom tag into the RichText field
3. On the custom tag attributes screen click the "Cancel" link
**Expected result**
Insert custom tag dialog is closed.
**Actual result**
Insert custom tag dialog stays on the screen and the following JavaScript error is thrown:
```
react-dom.production.min.js:32 Uncaught TypeError: Cannot read property 'setFocused' of null at …
```

IBX-962: New custom tag inserting
