ezsystems/ezplatform-richtext

.travis.yml, bin/.travis/prepare_unittest.sh, phpunit-integration-legacy.xml
| **JIRA issue**     | Part of [EZP-28009](https://jira.ez.no/browse/EZP-28009)
| **Target version** | `1.0`
| **Tests pass**     | TBD
The PR contains improvements to the Travis test setup matrix.
**TODO**:
=> [Travis] Improved test matrix setup

tests/bundle/DependencyInjection/Compiler/RichTextHtml5ConverterPassTest.php
| **JIRA issue**     | -
**TODO**:
=> Fixed incorrect namespace in RichTextHtml5ConverterPassTest

src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl, tests/bundle/DependencyInjection/EzPlatformRichTextExtensionTest.php, tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/023-embedInline.xml
This is a follow up fixing failures after changes from:
**TODO**:
=> [CI] Fixed failing CI

src/bundle/DependencyInjection/Configuration.php, src/bundle/DependencyInjection/EzPlatformRichTextExtension.php
| **JIRA issue**     | [EZP-30366](https://jira.ez.no/browse/EZP-30366)
| **Target version** | 2.5
It is related to https://github.com/ezsystems/ezplatform-admin-ui/pull/931
**TODO**:
=> EZP-30366: AlloyEditor Configurations

composer.json, src/lib/eZ/REST/FieldTypeProcessor/RichTextProcessor.php
> JIRA: https://jira.ez.no/browse/EZP-28034
Extract RestBundle and Common namespace to new package.
https://github.com/ezsystems/ezpublish-kernel/pull/2630
=> EZP-28034: Refactored to depend on EzPlatformRestBundle

.travis.yml
| **JIRA issue**     | n/a
| **Bug/Improvement**| -
Replacing existing SYMFONY_ENV and SYMFONY_DEBUG usage for Travis, to adjust for Symfony 4 changes.
**TODO**:
=> Changed variables to SF4 APP_ENV and APP_DEBUG

src/bundle/Resources/views/RichText/content_fields.html.twig, src/bundle/Templating/Twig/Extension/RichTextExtension.php
| **JIRA issue**     | [EZP-30627](https://jira.ez.no/browse/EZP-30627)
related to : https://github.com/ezsystems/ezplatform-admin-ui/pull/1008
**TODO**:
=> EZP-30627: Unified Twig helpers naming

tests/integration/eZ/API/SetupFactory/CoreSetupFactoryTrait.php
=> EZP-30646: Replaced SignalSlots with Events in integration tests setup factory

composer.json, tests/integration/eZ/API/SetupFactory/CoreSetupFactoryTrait.php
| **JIRA issue**     | [EZP-30829](https://jira.ez.no/browse/EZP-30829)
| **Bug**| yes
**TODO**:
=> EZP-30829: Fixed container configuration to allow integration tests pass

src/bundle/Resources/config/form.yaml, src/bundle/Resources/config/rest.yaml, src/lib/eZ/settings/fieldtype_external_storages.yaml, src/lib/eZ/settings/fieldtypes.yaml, src/lib/eZ/settings/indexable_fieldtypes.yaml, src/lib/eZ/settings/storage_engines/legacy/field_value_converters.yaml
| **JIRA issue**     | [EZP-30833](https://jira.ez.no/browse/EZP-30833)
Aligned Field Type service tags to the new naming convention introduced in https://github.com/ezsystems/ezpublish-kernel/pull/2653.
**TODO**:
=> EZP-30833: Aligned Field Type service tags to new naming convention

src/bundle/Resources/public/scss/_link-edit.scss
| **JIRA issue**     | [EZP-30959](https://jira.ez.no/browse/EZP-30959)
| **Bug**| yes
This PR is just code taken from https://github.com/ezsystems/ezplatform-admin-ui/pull/1105 against 3.0.
**TODO**:
=> EZP-30959: Long URL overlaps "clear URL input" button in Online Editor

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-linkedit.js
| **JIRA issue**     | [EZP-31054](https://jira.ez.no/browse/EZP-31054)
**TODO**:
=> EZP-31054: Cannot select content in AlloyEditor link in Page Builder

src/bundle/Resources/public/js/OnlineEditor/core/base-richtext.js
| **JIRA issue**     | [EZP-30859](https://jira.ez.no/browse/EZP-30859)
| **Target version** | lmaster
Merged up: https://github.com/ezsystems/ezplatform-admin-ui/pull/1125
**TODO**:
=> EZP-30859: Cannot remove formatting after publication in RTE

composer.json, src/lib/Form/Mapper/RichTextFormMapper.php
| **JIRA issue**     | [EZP-31010](https://jira.ez.no/browse/EZP-31010)
**TODO**:
=>  EZP-31010: Updated namespaces in ezplatform-richtext

src/bundle/Resources/public/js/OnlineEditor/plugins/base/ez-custom-tag-base.js, src/bundle/Resources/public/js/OnlineEditor/plugins/base/ez-embed-base.js, src/bundle/Resources/public/js/OnlineEditor/plugins/ez-custom-tag.js
| **JIRA issue**     | [EZP-31058](https://jira.ez.no/browse/EZP-31058)
| **Bug**| yes
Merge up: https://github.com/ezsystems/ezplatform-admin-ui/pull/1137
**TODO**:
=> EZP-31058: No new line can be inserted in RTE below custom tags

src/bundle/DependencyInjection/Configuration/Parser/FieldType/RichText.php, src/lib/Configuration/UI/Mapper/CustomStyle.php, src/lib/Configuration/UI/Mapper/CustomTag.php, src/lib/eZ/RichText/Validator/InternalLinkValidator.php, src/lib/eZ/RichText/Validator/Validator.php, tests/bundle/DependencyInjection/Configuration/Parser/FieldType/RichTextTest.php, tests/integration/eZ/API/RichTextFieldTypeIntegrationTest.php, tests/integration/eZ/API/SetupFactory/CoreSetupFactoryTrait.php, tests/lib/eZ/FieldType/RichTextTest.php, tests/lib/eZ/RichText/Validator/InternalLinkValidatorTest.php
| **JIRA issue**     | [EZP-31021](https://jira.ez.no/browse/EZP-31021)
| **Tests pass**     | yes/no
Main PR: https://github.com/ezsystems/ezpublish-kernel/pull/2878
**TODO**:
~- [ ] Implement feature / fix a bug.~
~- [ ] Implement tests.~
~- [ ] Fix new code according to Coding Standards (`$ composer fix-cs`).~
=> EZP-31021: Revise exception & command microcopy

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-anchoredit.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-embed.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-embedinline.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-embedupdate.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-imageupdate.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-movedown.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-moveup.js, src/bundle/Resources/translations/alloy_editor.en.xlf, src/bundle/Resources/translations/custom_tags.en.xlf
| **JIRA issue**     | [EZP-31020](https://jira.ez.no/browse/EZP-31020)
| **Target version** |  master
| **Tests pass**     | yes/no
https://github.com/ezsystems/ezplatform-admin-ui/pull/1115
=> EZP-31020: Revised UI labels and messages

src/bundle/Resources/public/js/OnlineEditor/core/base-richtext.js
| **JIRA issue**     | [EZP-31096](https://jira.ez.no/browse/EZP-31096)
https://github.com/ezsystems/ezplatform-admin-ui/pull/1124
**TODO**:
=> EZP-31096: Custom toolbars in Alloy Editor

tests/bundle/DependencyInjection/Configuration/Parser/FieldType/RichTextTest.php
| **JIRA issue**     | [EZP-31046](https://jira.ez.no/browse/EZP-31046)
| **Bug/Improvement**|no
| **BC breaks**      |no
| **Doc needed**     |no
| **Related to**     | https://github.com/ezsystems/ezpublish-kernel/pull/2901
**TODO**:
=> EZP-31046: Removed usage of `ezpublish.config.resolver.core`

src/bundle/Resources/public/scss/_alloyeditor-ez.scss
| **JIRA issue**     | https://jira.ez.no/browse/EZP-31187
Changed margins for embedded widget.
**TODO**:
=> EZP-31187: Changed margins for embedded

src/bundle/Resources/public/scss/_custom-tag.scss
| **JIRA issue**     | https://jira.ez.no/browse/EZP-31188
Change padding in custom tag buttons
**TODO**:
=> EZP-31188: Change padding in custom tag buttons

src/bundle/Resources/public/js/OnlineEditor/buttons/base/ez-embeddiscovercontent.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-linkedit.js
| **JIRA issue**     | [EZP-31215](https://jira.ez.no/browse/EZP-31215)
| **New feature**    | yno
**TODO**:
=> EZP-31215: Remove old UDW and deprecated code

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-imagelinkedit.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-linkedit.js
| **JIRA issue**     | [EZP-31056](https://jira.ez.no/browse/EZP-31056)
Changes from https://github.com/ezsystems/ezplatform-admin-ui/pull/1114 targeted to eZ Platform 3.0.
**TODO**:
=> EZP-31056: Link is added to the text in RTE despite not choosing any content via UDW

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-anchoredit.js, src/bundle/Resources/public/scss/_anchor-edit.scss, src/bundle/Resources/public/scss/variables/colors.scss, src/bundle/Resources/translations/alloy_editor.en.xlf
| **JIRA issue**     | https://jira.ez.no/browse/EZP-30485
Changes from admin-ui 2.5 moved to richtext 3.0
**TODO**:
=> EZP-30485: Added validation for anchor link

src/bundle/Resources/public/js/OnlineEditor/core/base-richtext.js
| **JIRA issue**     | [EZP-31371](https://jira.ez.no/browse/EZP-31371)
This is targetting for eZ Platform 3.0, followup for https://github.com/ezsystems/ezplatform-admin-ui/pull/1245.
**TODO**:
=> EZP-31371: Copying a web page link w/o protocol in a Word paragraph leads to a 404 error

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-imagelinkedit.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-linkedit.js
| **JIRA issue**     | [EZP-31409](https://jira.ez.no/browse/EZP-31409)
**TODO**:
=> EZP-31409: Cannot select content item in link to image

src/bundle/Resources/views/RichText/embed/content.html.twig, src/bundle/Resources/views/RichText/embed/location.html.twig, src/bundle/Resources/views/RichText/embed/location_inline.html.twig
JIRA: https://jira.ez.no/browse/EZP-30639
=> EZP-30639: Used Content view instead of deprecated Location view

src/bundle/Resources/public/js/OnlineEditor/toolbars/config/base-fixed.js, src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-heading.js, src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-paragraph.js
| **JIRA issue**     | [EZP-31066](https://jira.ez.no/browse/EZP-31066)
This is a followup for https://github.com/ezsystems/ezplatform-admin-ui/pull/1267 targeting eZ Platform 3.0.
**TODO**:
=> EZP-31066: Error when clicking the link in RTE

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-imageupdate.js
| **JIRA issue**     | [EZP-31120](https://jira.ez.no/browse/EZP-31120)
This is a followup for: https://github.com/ezsystems/ezplatform-admin-ui/pull/1327 targeting 3.0.
**TODO**:
=> EZP-31120: Image is not replaced in RTE/OE when publishing directly

src/bundle/Resources/public/js/OnlineEditor/plugins/base/ez-embed-base.js
| **JIRA issue**     | [EZP-31183](https://jira.ez.no/browse/EZP-31183)
**TODO**:
=> EZP-31183: Removed dropped Criteria from REST calls

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-embed.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-embedinline.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-embedupdate.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-image.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-imageupdate.js, src/bundle/Resources/translations/alloy_editor.en.xliff
| **JIRA issue**     | https://jira.ez.no/browse/EZP-29475
Merge up for https://github.com/ezsystems/ezplatform-admin-ui/pull/1346
**TODO**:
=> EZP-29475: Changes for UDW title

src/bundle/Resources/public/js/OnlineEditor/plugins/base/ez-embed-base.js, src/bundle/Resources/translations/alloy_editor.en.xliff
| **JIRA issue**     | [EZP-31626](https://jira.ez.no/browse/EZP-31626)
Merge up: https://github.com/ezsystems/ezplatform-admin-ui/pull/1374
**TODO**:
=> EZP-31626: Fixed error in AlloyEditor when embed location

src/bundle/Resources/public/js/OnlineEditor/core/base-richtext.js
| **JIRA issue**     | [EZP-31405](https://jira.ez.no/browse/EZP-31405)
This is merge up to 3.0 from the https://github.com/ezsystems/ezplatform-admin-ui/pull/1255 
**TODO**:
=> EZP-31405: fix embed image link removal

.travis.yml
| **JIRA issue**     |-
Updated Solr version to 7.7.3 in .travis.yml
**TODO**:
=> Updated Solr version to 7.7.3 in .travis.yml

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-anchoredit.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-customtag-update.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-imagevariation.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-linkedit.js, src/bundle/Resources/public/scss/_alloyeditor-ez.scss, src/bundle/Resources/public/scss/_anchor-edit.scss, src/bundle/Resources/public/scss/_attributes.scss, src/bundle/Resources/public/scss/_buttons.scss, src/bundle/Resources/public/scss/_custom-styles.scss, src/bundle/Resources/public/scss/_custom-tag.scss, src/bundle/Resources/public/scss/_inputs.scss, src/bundle/Resources/public/scss/_link-edit.scss, src/bundle/Resources/public/scss/alloyeditor.scss, src/bundle/Resources/public/scss/functions/checkbox-switcher.scss, src/bundle/Resources/public/scss/variables/colors.scss, src/bundle/Resources/public/scss/variables/vars.scss
jira ref: https://jira.ez.no/browse/EZP-31774
=> EZP-31774: redesign richtext

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-anchoredit.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-customtag-update.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-imagevariation.js, src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-linkedit.js, src/bundle/Resources/public/scss/_alloyeditor-ez.scss, src/bundle/Resources/public/scss/_anchor-edit.scss, src/bundle/Resources/public/scss/_attributes.scss, src/bundle/Resources/public/scss/_buttons.scss, src/bundle/Resources/public/scss/_custom-styles.scss, src/bundle/Resources/public/scss/_custom-tag.scss, src/bundle/Resources/public/scss/_inputs.scss, src/bundle/Resources/public/scss/_link-edit.scss, src/bundle/Resources/public/scss/alloyeditor.scss, src/bundle/Resources/public/scss/functions/checkbox-switcher.scss, src/bundle/Resources/public/scss/variables/colors.scss, src/bundle/Resources/public/scss/variables/vars.scss
| **JIRA issue**     | [EZP-31721](https://jira.ez.no/browse/EZP-31721)
**TODO**:
=> EZP-31721: New UI

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
| **JIRA issue**     | [EZP-32366](https://jira.ez.no/browse/EZP-32366)
**TODO**:
=> EZP-32366: As an Editor, I want to use basic features of CKEditor5

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/js/CKEditor/plugins/elements-path.js
| **JIRA issue**     | [EZP-32376](https://jira.ez.no/browse/EZP-32376)
**TODO**:
=> EZP-32376: As an Editor, I want to see elements path

src/bundle/Resources/encore/ez.webpack.custom.config.js, src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-command.js, src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-editing.js, src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-ui.js, src/bundle/Resources/public/js/CKEditor/embed/content/embed-command.js, src/bundle/Resources/public/js/CKEditor/embed/content/embed-editing.js, src/bundle/Resources/public/js/CKEditor/embed/content/embed-ui.js, src/bundle/Resources/public/js/CKEditor/embed/embed-base-ui.js, src/bundle/Resources/public/js/CKEditor/embed/embed.js, src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-command.js, src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js, src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-toolbar.js, src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-ui.js, src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-variations-ui.js, src/bundle/Resources/public/js/CKEditor/plugins/character-counter.js, src/bundle/Resources/public/js/CKEditor/plugins/elements-path.js, src/bundle/Resources/public/js/CKEditor/services/content-service.js, src/bundle/Resources/public/scss/ckeditor/_general.scss, src/bundle/Resources/public/scss/ckeditor/ckeditor.scss
| **JIRA issue**     | [IBX-98](https://jira.ez.no/browse/IBX-98)
**TODO**:
=> IBX-98: As an Editor, I want to embed content into richtext

src/bundle/Resources/public/js/CKEditor/common/input-number/input-number-view.js, src/bundle/Resources/public/js/CKEditor/common/input-number/utils.js, src/bundle/Resources/public/js/CKEditor/common/switch-button/utils.js, src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/js/CKEditor/custom-tags/custom-tag-command.js, src/bundle/Resources/public/js/CKEditor/custom-tags/custom-tag-editing.js, src/bundle/Resources/public/js/CKEditor/custom-tags/custom-tag-ui.js, src/bundle/Resources/public/js/CKEditor/custom-tags/custom-tags.js, src/bundle/Resources/public/js/CKEditor/custom-tags/ui/custom-tag-form-view.js, src/bundle/Resources/public/scss/ckeditor/_custom-tag.scss, src/bundle/Resources/public/scss/ckeditor/ckeditor.scss
| **JIRA issue**     | [IBX-213](https://jira.ez.no/browse/IBX-213)
| **Target version** | 4.0
**TODO**:
=> IBX-213: As an Editor, I want to add custom tag

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/js/CKEditor/custom-tags/custom-tag-command.js, src/bundle/Resources/public/js/CKEditor/custom-tags/custom-tag-editing.js, src/bundle/Resources/public/js/CKEditor/custom-tags/custom-tag-ui.js, src/bundle/Resources/public/js/CKEditor/custom-tags/custom-tags.js, src/bundle/Resources/public/js/CKEditor/custom-tags/ui/custom-tag-form-view.js, src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-command.js, src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-editing.js, src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-ui.js, src/bundle/Resources/public/js/CKEditor/embed/content/embed-command.js, src/bundle/Resources/public/js/CKEditor/embed/content/embed-editing.js, src/bundle/Resources/public/js/CKEditor/embed/content/embed-ui.js, src/bundle/Resources/public/js/CKEditor/embed/embed-base-ui.js, src/bundle/Resources/public/js/CKEditor/embed/embed.js, src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-command.js, src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js, src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-toolbar.js, src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-ui.js, src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-variations-ui.js, src/bundle/Resources/public/js/CKEditor/link/link-command.js, src/bundle/Resources/public/js/CKEditor/link/link-editing.js, src/bundle/Resources/public/js/CKEditor/link/link-ui.js, src/bundle/Resources/public/js/CKEditor/link/link.js, src/bundle/Resources/public/js/CKEditor/link/ui/link-form-view.js, src/bundle/Resources/public/js/CKEditor/plugins/character-counter.js, src/bundle/Resources/public/js/CKEditor/plugins/elements-path.js
| **JIRA issue**     | [IBX-316](https://jira.ez.no/browse/IBX-316)
| **Target version** | 4.0
**TODO**:
=> IBX-316: As an Editor, I want to add link

src/bundle/Resources/public/js/OnlineEditor/toolbars/config/base.js
| **JIRA issue**     | [EZP-32387](https://jira.ez.no/browse/EZP-32387)
| **Target version** | `3.3`, `master`
This is a follow-up for https://github.com/ezsystems/ezplatform-admin-ui/pull/1778 targetting v3.3.
**TODO**:
=> EZP-32387: Fixed text block toolbar alignment

src/bundle/Resources/public/js/CKEditor/anchor/anchor-editing.js, src/bundle/Resources/public/js/CKEditor/anchor/anchor-ui.js, src/bundle/Resources/public/js/CKEditor/anchor/anchor.js, src/bundle/Resources/public/js/CKEditor/anchor/ui/anchor-form-view.js, src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/scss/ckeditor/_general.scss
| **JIRA issue**     | [IBX-403](https://jira.ez.no/browse/IBX-403)
**TODO**:
=> IBX-403: As an Editor, I want to anchor element in richtext

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/js/CKEditor/custom-styles/inline/custom-style-inline-editing.js, src/bundle/Resources/public/js/CKEditor/custom-styles/inline/custom-style-inline-ui.js, src/bundle/Resources/public/js/CKEditor/custom-styles/inline/custom-styles-inline.js, src/bundle/Resources/public/js/CKEditor/custom-tags/custom-tag-editing.js
| **JIRA issue**     | [IBX-404](https://jira.ez.no/browse/IBX-404)
**TODO**:
=> IBX-404: As an Editor, I want to add custom style

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/js/CKEditor/custom-tags/custom-tag-editing.js, src/bundle/Resources/public/js/CKEditor/formatted/formatted-command.js, src/bundle/Resources/public/js/CKEditor/formatted/formatted-editing.js, src/bundle/Resources/public/js/CKEditor/formatted/formatted-ui.js, src/bundle/Resources/public/js/CKEditor/formatted/formatted.js
| **JIRA issue**     | [IBX-583](https://jira.ez.no/browse/IBX-583)
**TODO**:
=> IBX-583: Implemented formatted text support for CKEditor5

README.md
| **JIRA issue**     | N/A
| **Tests pass**     | yes (nothing to test)
| **Doc needed**     | yes (doc update/fix)
Update link to Docbook schemas dir and Resources dir (where can be found DTD and other schemas)
**TODO**:
=> README.md: Update link to Resources

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-command.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-editing.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-ui.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/ui/custom-attributes-form-view.js
| **JIRA issue**     | [IBX-584](https://jira.ez.no/browse/IBX-584)
**TODO**:
=> IBX-584: Implemented support for custom attributes

.travis.yml
JIRA: https://issues.ibexa.co/browse/IBX-264
Requires: https://github.com/ezsystems/ezplatform-admin-ui/pull/1802
Running tests marked with `@richtext` as a job in this PR, as it was previosly.
~~TODO: remove TMP commit~~
=> [Travis] Changed suite to the new approach

src/bundle/Resources/config/bazinga_js_translation.yaml, src/bundle/Resources/encore/ez.webpack.custom.config.js, src/bundle/Resources/public/js/CKEditor/anchor/anchor-ui.js, src/bundle/Resources/public/js/CKEditor/common/button-view/button-view.js, src/bundle/Resources/public/js/CKEditor/common/icon-view/icon-view.js, src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-ui.js, src/bundle/Resources/public/js/CKEditor/custom-styles/inline/custom-style-inline-ui.js, src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js, src/bundle/Resources/public/js/CKEditor/custom-tags/inline-custom-tag/inline-custom-tag-ui.js, src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-ui.js, src/bundle/Resources/public/js/CKEditor/embed/content/embed-ui.js, src/bundle/Resources/public/js/CKEditor/embed/embed-base-ui.js, src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-ui.js, src/bundle/Resources/public/js/CKEditor/formatted/formatted-ui.js, src/bundle/Resources/public/js/CKEditor/link/link-ui.js, src/bundle/Resources/translations/ck_editor.en.xliff
| **JIRA issue**     | [IBX-770](https://jira.ez.no/browse/IBX-770)
**TODO**:
=> IBX-770: Added icons to buttons

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/js/CKEditor/move/move-command.js, src/bundle/Resources/public/js/CKEditor/move/move-down-ui.js, src/bundle/Resources/public/js/CKEditor/move/move-editing.js, src/bundle/Resources/public/js/CKEditor/move/move-up-ui.js, src/bundle/Resources/public/js/CKEditor/move/move.js, src/bundle/Resources/translations/ck_editor.en.xliff
| **JIRA issue**     | [IBX-788](https://jira.ez.no/browse/IBX-788)
**TODO**:
=> IBX-788: Implemented support for moving elements

src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-linkedit.js, src/bundle/Resources/public/js/OnlineEditor/plugins/ez-caret.js
| **JIRA issue**     | [IBX-824](https://jira.ez.no/browse/IBX-824)
| **Target version** | `2.3`, `master`
Followup for https://github.com/ezsystems/ezplatform-admin-ui/pull/1872 targeting v3.
**TODO**:
- ~[ ] Implement tests~.
=> IBX-824: Fixed triggering closing link popup on formatted text

src/bundle/Resources/translations/ck_editor.en.xliff
| **JIRA issue**     | N/A
| **Bug/Improvement**| yes/no
| **New feature**    | yes/no
| **BC breaks**      | yes/no
| **Tests pass**     | yes/no
| **Doc needed**     | yes/no
**TODO**:
=> Updated translations

src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-link.js
| **JIRA issue**     | [IBX-1062](https://issues.ibexa.co/browse/IBX-1062)
| **Target version** | 2.3
`- 10` added to show whole popup without cutting border
**TODO**:
=> IBX-1062: Corrected set position for confirm popup for link
